version: "3.9"
services:
  node:
    build: ./node
    stdin_open: true
    tty: true
    volumes: 
      - ./node_vol:/node_vol
    container_name: node14
    environment:
    - TZ=Asia/Taipei
    links:
      - mongo

  mongo:
    image: mongo:4.0.4
    restart: always
    container_name: mongo
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
    environment:
    - TZ=Asia/Taipei
    #   - MONGO_INITDB_ROOT_USERNAME=YouShin
    #   - MONGO_INITDB_ROOT_PASSWORD=M11007317

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   container_name: mongo-express
  #   links:
  #     - mongo
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=YouShin
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=M11007317
  #     - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
  #     - ME_CONFIG_MONGODB_URL=mongodb://YouShin:M11007317@mongo:27017/
  #   depends_on:
  #     - mongo

